## Tensors

* similar to NumPy's ndarrays
* pytorch tensors can accerlerate GPG computing
* ```  torch.syntax(x, y) ```

---

- [ ] what is dtype
- [ ] what is a tuple operator

---

-- [blitz](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [1]:
from __future__ import print_function
import torch


# 5 x 3 matrix, uninitialized
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.1704e-41, 0.0000e+00, 2.2369e+08],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [2]:
# random initialized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.0925, 0.8708, 0.6124],
        [0.4057, 0.2797, 0.5092],
        [0.9871, 0.6832, 0.6578],
        [0.4032, 0.2646, 0.8911],
        [0.2479, 0.2078, 0.0879]])


In [3]:
# zeros, dtype long matrix
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
# tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [31]:
# new tensor, from tensor

# dtype = new size
x = x.new_ones(5, 3, dtype = torch.double)
print(x)
print()

# new dtype = x inputs randomized
# matrix still same size
x = torch.randn_like(x, dtype = torch.float)
print(x)
print()

# torch.size = tuple operator
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

tensor([[-0.4090,  0.5867,  1.2171],
        [-0.6665,  0.9825,  0.5570],
        [-1.0807,  0.3264,  0.1208],
        [ 0.9368,  2.9475,  0.4683],
        [ 1.0758,  0.2566, -0.2496]])

torch.Size([5, 3])


#### Operators


In [42]:
# syntax 01
y = torch.rand(5, 3)
print('x + y :')
print(x + y)
print()


# syntax 02
print('torch.add(x, y) :')
print(torch.add(x, y))
print()

# arg
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print('result :')
print(result)
print()

# mutate tensor 'x' with x.copy_(y), x.t_()
y.add_(x)
print('y :')
print(y)
print()


x + y :
tensor([[2.7497, 2.7621, 2.7812],
        [2.3754, 2.6857, 2.2906],
        [2.6309, 2.2168, 2.5430],
        [2.3221, 2.3671, 1.9226],
        [2.7480, 2.0740, 1.9840]])

torch.add(x, y) :
tensor([[2.7497, 2.7621, 2.7812],
        [2.3754, 2.6857, 2.2906],
        [2.6309, 2.2168, 2.5430],
        [2.3221, 2.3671, 1.9226],
        [2.7480, 2.0740, 1.9840]])

result :
tensor([[2.7497, 2.7621, 2.7812],
        [2.3754, 2.6857, 2.2906],
        [2.6309, 2.2168, 2.5430],
        [2.3221, 2.3671, 1.9226],
        [2.7480, 2.0740, 1.9840]])

y :
tensor([[2.7497, 2.7621, 2.7812],
        [2.3754, 2.6857, 2.2906],
        [2.6309, 2.2168, 2.5430],
        [2.3221, 2.3671, 1.9226],
        [2.7480, 2.0740, 1.9840]])



In [46]:

# index using standard numpy
print('Numpy index x[:, 1] :', x [:, 1])
print() 


# resize/reshape tensor with 'torch.view'
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
# -1 infers another dimension
print('resize/reshape tensor with "x.view" :', x.size(), y.size(), z.size())
print()


# get py number for one element tensor with 'x.item()'
x = torch.randn(1)
print('x : ', x)
print('one element tensor as py number x.item() : ', x.item())

IndexError: too many indices for tensor of dimension 1

### NumPy Bridge

* convert torch tensor into numpy array
* memory locations shared

##### Convert Torch Tensor to NumPy Array

In [50]:
# tensor
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [51]:
# numpy
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [53]:
# change np array value to test
a.add_(1)
print('a = torch.ones(5) :', a)
print('b = a.numpy() :', b)

a = torch.ones(5) : tensor([3., 3., 3., 3., 3.])
b = a.numpy() : [3. 3. 3. 3. 3.]


##### Convert NumPy Array to Torch Tensor

In [58]:
import numpy as np

# numpy array
a = np.ones(5)
# torch
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


#### CUDA Tensors
* move tensors onto any device with ```.to``` method

In [59]:
# check if CUDA is available
# if available, move tensor from one GPU device to another with 'torch.device' object

if torch.cuda.is_available():
    # device = cuda object
    device = torch.device('cuda')
    # create new tensor on GPU device
    y = torch.ones_like(x, device = device)
    # to cuda device
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))
    
# Total running time of the script should be 0 minutes 6.500 seconds, if cuda available
# https://is.gd/1hW75p



## AutoGrad

##### Automatic Differentiation

* vector(v)-Jacobian (matrix) product ( vT ⋅ J ) a row vector, ( JT ⋅ v ) a column vector === easy to feed external gradients into non-scalar output model
* v = gradient of scalar function ->  v = ( ∂𝓁 / ∂y₁ ⋯ ∂𝓁 / ∂ym ) T  -> 𝓁 = g ( ⃗y )
* nn pkg
* ``` torch.Tensor ```
* don't need gradient computing when evaluating model with trainable parameters (``` requires_grad = True ```)

Class Commands

* ``` .tensor ``` == function as ``` .grad_fn ``` = creates acyclic graph & encodes computational history
    * ``` .grad_fn ``` = function attribute inside tensor
* ``` .requires_grad = True ``` = tracks all operations 
* ``` .backward() ``` = auto computes gradient derivatives from tensor
    * no (arguments) if a scalar (one element data tensor)
    * matching array/tensor shape in gradient argument if 2+ element data in tensor
* ``` .grad ``` = holds tensor (array) values
* ``` .detach() ``` = stop tracking operations immediately & completely
* ``` with torch.no_grad(): ``` = prevent tracking & memory use






In [69]:
#import torch

#(rows, cols)

# create tensor & track computation
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [71]:
# y tensor operation = array function
y = x + 2
print('y :', y)
print()

# compute y gradient
print('y.grad_fn :', y.grad_fn)
print()

# calculate mean inside y as a function
z = y * y * 3
out = z.mean()
print('z :', z)
print('out : ', out)

y : tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

y.grad_fn : <AddBackward0 object at 0x10efb5f60>

z : tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
out :  tensor(27., grad_fn=<MeanBackward0>)


In [92]:
a = torch.randn(2, 2)
print('1.] a = torch.randn(2, 2) :', a)
print()

a = ((a * 3) / (a -1))
print('2.] a = ((a * 3) / (a -1)) :', a)
print()

print('3.] a.requires_grad :', a.requires_grad)
print()

a.requires_grad_(True)

print('4.] a.requires_grad_(True) :', a.requires_grad_(True))
print()

print('5.] a.requires_grad :', a.requires_grad)
print()

b = (a * a).sum()
print('6.] b = (a * a).sum() :', b)
print()

# tensor function
print('7.] b.grad_fn :', b.grad_fn)
print()



1.] a = torch.randn(2, 2) : tensor([[ 1.4067,  1.5736],
        [-0.6415,  0.8988]])

2.] a = ((a * 3) / (a -1)) : tensor([[ 10.3768,   8.2304],
        [  1.1724, -26.6577]])

3.] a.requires_grad : False

4.] a.requires_grad_(True) : tensor([[ 10.3768,   8.2304],
        [  1.1724, -26.6577]], requires_grad=True)

5.] a.requires_grad : True

6.] b = (a * a).sum() : tensor(887.4255, grad_fn=<SumBackward0>)

7.] b.grad_fn : <SumBackward0 object at 0x10efc59b0>



### Gradients: 

* backloop / back-propragation
* d(out) / dx, where ```o``` = ⃗y =f( ⃗x ) (vector valued function) = Jacobian Matrix
\begin{split}J=\left(\begin{array}{ccc}
 \frac{\partial y_{1}}{\partial x_{1}} & \cdots & \frac{\partial y_{1}}{\partial x_{n}}\\
 \vdots & \ddots & \vdots\\
 \frac{\partial y_{m}}{\partial x_{1}} & \cdots & \frac{\partial y_{m}}{\partial x_{n}}
 \end{array}\right)\end{split} →  \begin{split}J^{T}\cdot v=\left(\begin{array}{ccc}
 \frac{\partial y_{1}}{\partial x_{1}} & \cdots & \frac{\partial y_{m}}{\partial x_{1}}\\
 \vdots & \ddots & \vdots\\
 \frac{\partial y_{1}}{\partial x_{n}} & \cdots & \frac{\partial y_{m}}{\partial x_{n}}
 \end{array}\right)\left(\begin{array}{c}
 \frac{\partial l}{\partial y_{1}}\\
 \vdots\\
 \frac{\partial l}{\partial y_{m}}
 \end{array}\right)=\left(\begin{array}{c}
 \frac{\partial l}{\partial x_{1}}\\
 \vdots\\
 \frac{\partial l}{\partial x_{n}}
 \end{array}\right)\end{split}
* linear regression ??
* ``` out() ``` = single scalar
* ``` out.backward(torch.tensor(1.)) ``` 

In [ ]:

# 2+ element data in tensor
# out.backward()

# print gradient of d(out) / dx
# print(x.grad)


In [ ]:
# v = vector-Jacobian product

x = torch.randn(3, requires_grad = True)
print('torch.randn(3, requires_grad = True) :')
print(x)
print()

y = x * 2
print('y = x * 2 :', y)

while y.data.norm() < 1000:
    # print(y.data.norm())
    y = y * 2
    
print(y)